server:
  port: 8082

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: "postgres"
    password: "justForWork"
